### ISSUE TITLE
Pixabay images stop working after some time.

### ISSUE THREAD

**Issue by staffj01** [vassbo/freeshow#1879]
Added Pixabay images to show slide/s.
After some time noticed that the images were no longer loading.

To reproduce - create a show with slides in it. Drag and drop a pixabay image from the media drawer to the first slide to put it as a background.
Save the show, and add the show to a project.

Open the saved show within that project some time later - after some time (maybe 24 hours?), the image no longer loads.
Looking at an export of the project, the show contains links to the pixabay images within the project.
If I copy and paste these links into a web browser, I get an error page saying "This URL is invalid or has expired."

Is there a way that the  pixabay image links can be more long lasting, if not permanent?

**Version (Optional)**
 - OS: Windows 11
 - FreeShow Version: 1.4.7

**Comment by vassbo** [comment]
In the next version online images/videos will be cached locally, which should fix this as well.

https://github.com/ChurchApps/FreeShow/issues/1870

**Comment by staffj01** [comment]
Running Version 1.4.8 now.
I have tested some more online images - however there still appears to be some issues after some time passes.
This time, if I open a project that I created (using version 1.4.8) that includes online backgrounds from Pixabay a few days later, the Pixabay backgrounds show up in the output of the program, but do not appear in the thumbnails of the show, or in the edit window.
In contrast, the Unsplash images work as expected.

<img width="1296" height="785" alt="Image" src="https://github.com/user-attachments/assets/68f643ed-58a8-4c6b-8d3c-81b695beab56" />

<img width="1299" height="785" alt="Image" src="https://github.com/user-attachments/assets/dca7017b-f319-4b37-ab5f-efe8fb17b206" />
