### ISSUE TITLE
PCO syncing doesn't sync the correct VERSION of a song

### ISSUE THREAD

**Issue by jorbje** [vassbo/freeshow#2120]
**Describe the bug**
For some songs in PCO we have two or three versions (like different languages for instance). Last sunday our worship leader chose the English version of a couple of songs in PCO, but I got the Norwegian versions in Freeshow. Could it be that Freeshow only syncs the first version of songs regardless of which version that actually is used in the setlist?

**Version (Optional)**
 - FreeShow Version: 1.4.3

**Comment by vassbo** [comment]
Thanks, that might be the case. I do recommend testing it in the latest version though!

@Auxority Is this something you would like to check out?

**Comment by Auxority** [comment]
What I usually do is delete the show belonging to the song, but that’s not ideal of course. We could really benefit from this feature too, but I don’t have time to develop this shortly.

**Comment by Auxority** [comment]
Nevermind just checked, it always seems to use the first arrangement of a song. Hope to find some time next week to look into this, otherwise the value of arrangements is not really there for us.

**Comment by Auxority** [comment]
I think I found the root cause, looks like we just fetch the first arrangement here in the `processSongItem` method.

```ts
    const songDataEndpoint = `${itemsEndpoint}/${item.id}/song`
    const songData = (await pcoRequest({ scope: "services", endpoint: songDataEndpoint }))[0]
    if (!songData?.id) return null

    const arrangementEndpoint = `/songs/${songData.id}/arrangements`
    const songArrangement = (await pcoRequest({ scope: "services", endpoint: arrangementEndpoint }))[0]
    if (!songArrangement?.id) return null
```

Will try to fix it after dinner.

**Comment by vassbo** [comment]
@jorbje Might be working?: https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.0-beta.3

**Comment by Auxority** [comment]
Works for me 😄 

_Now just gotta get my development environment working again 😢_

**Comment by vassbo** [comment]
Cool, thanks for the help.

**Comment by jorbje** [comment]
Great. This partly works for me now. It will now download the correct version, but it wont update if the plan is allready synced a first time. I have to delete the "show" first.

And there is still one bug left for me: It wont sync the whole plan:

<img width="280" height="786" alt="Image" src="https://github.com/user-attachments/assets/6c4d537b-a7db-4b79-993b-f424151cfdbd" />

<img width="551" height="810" alt="Image" src="https://github.com/user-attachments/assets/ed2df45c-d936-4261-b601-2197d349eec3" />

**Comment by vassbo** [comment]
Nice. Looks like it caps it at 25 items for some reason, probably a default limit we can increase..

**Comment by vassbo** [comment]
A different thing: I also added section times in the beta, I see that it will be good to automatically convert any prefixed times like "11:20 Lovsang" to the time "11:20" and title "Lovsang", that way the program will automatically count towards the time, and the time left can be shown on the stage display.

**Comment by vassbo** [comment]
<img width="829" height="159" alt="Image" src="https://github.com/user-attachments/assets/d7b1dc64-0f94-4bb0-b03d-a2271a02c964" />

**Comment by vassbo** [comment]
@Auxority I guess we can just add `params: { per_page: "100" }`, but that would cap it at 100, so maybe we should do the pagination properly? If you don't mind checking it out. :)

**Comment by vassbo** [comment]
I think 100 is plenty though..

**Comment by jorbje** [comment]
The text "11:20 Lovsang" is written entirely by us because PCO doesn't support time stamps in headings. We only use these times as a guide. We have no need for any countdown or automation or whatever, but maybe other also put time in their headers and want to use it for something in Freeshow?

**Comment by vassbo** [comment]
Yes, I was just thinking it would be nice generally.

**Comment by vassbo** [comment]
@jorbje Should be working I hope: https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.0-beta.4

**Comment by jorbje** [comment]
Yes! I get the whole list now, with the correct version. But it still wont update though if someone changes version. (Yes I know I have to click the update button in settings). And I have lost the thumbnail preview in the top right corner.

**Comment by Auxority** [comment]
@jorbje that’s still on the To-Do list, but that would probably be a bigger change. Haven’t gotten around to that yet.
