### ISSUE TITLE
Performance Issue with freeShow v1.4.9

### ISSUE THREAD

**Issue by JoJo26josh** [vassbo/freeshow#2123]
Hi Freeshow Team

I’m experiencing a performance issue with the latest version of FreeShow (v1.4.9). After installing it and using it once for a service, the software becomes extremely laggy upon subsequent use. I’m unable to click, scroll, or project output effectively.

For reference, my laptop specs are as follows:

* **CPU:** Intel i5-12th Gen
* **GPU:** RTX 3050
* **RAM:** 16 GB
* **Storage:** 256 GB

I’ve tried previous versions as well, and the issue persists. I’m unsure if it’s related to my hardware or something else. Could you please assist me in troubleshooting this problem?

Can anyone help!

**Comment by vassbo** [comment]
Should be fixed here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.0-beta.2

**Comment by JoJo26josh** [comment]
Hello free show Team,

I hope you're doing well. I wanted to share some feedback regarding the recent beta update. While I appreciate the improvements, I'm still experiencing significant lag issues in certain scenarios. Specifically:

Media Handling: When adding or opening new media, the system takes a long time to respond.

Live Output: When starting live output, lag becomes more noticeable, making it difficult to move or interact smoothly.

Panel Performance: Adding new shows or elements to the panel causes severe lag, and scrolling, editing text, or even creating or closing new slides becomes impossible. The system essentially becomes stuck, and I cannot perform any actions.

These problems are impacting the usability and workflow significantly, and I hope this feedback helps in identifying and resolving these issues in future updates.

Thank you for your continued support and efforts.

**Comment by vassbo** [comment]
Can you check the task manager what the usage looks like?

**Comment by vassbo** [comment]
Try this: Go to settings>Other toggle "Disable hardware acceleration" and reopen the program.

**Comment by JoJo26josh** [comment]
<img width="1600" height="869" alt="Image" src="https://github.com/user-attachments/assets/db3919da-4d54-4163-b0f7-c834dfa45522" />


This the usage.

**Comment by JoJo26josh** [comment]
<img width="1919" height="1021" alt="Image" src="https://github.com/user-attachments/assets/b1a68361-b7b9-4b3b-bc61-26ec5a71fed8" />

I cant find hardware acceleration or Disable hardware acceleration. Can help me out.

**Comment by gladsonsam** [comment]
![491472672-b1a68361-b7b9-4b3b-bc61-26ec5a71fed8.png](https://github.com/user-attachments/assets/a85d16d6-a985-4c90-8289-02c2b3d17369)

It is the option inside the white box!

**Comment by JoJo26josh** [comment]
thank you sm for helping me out .
